### ISSUE TITLE
Copy & Paste as HTML (for Excel)

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#338]
A feature request from the survey:

> To clarify the feature request on copying interlinear to Word/Excel: this is maybe specific to the particular layout used in INEL, but what we need does not work so much with Ctrl-C. Suppose I'm trying to copy this sentence:

![image](https://user-images.githubusercontent.com/13796493/197972966-bc3b8581-6538-4b0b-9fbc-e20570432fe0.png)

> As you can see in the screenshot, I've got here one long annotation for the sentence (e.g. full text, translation and reference) spanning three individual events for each word.
When I try to copy and paste it into Excel, I get this:

![image](https://user-images.githubusercontent.com/13796493/197973014-cffee5b1-f083-4f57-8d11-810ca68ad5fb.png)

> with everything in one column, instead of three columns (one per word). And since there are no leading or trailing spaces except in transcription tier, there are no delimiters whatsoever in the result, so I must recover word boundaries manually...

May be possible to transfer sumpin from EXACT's copy & paste.

**Comment by berndmoos** [comment]
And for Copy&Paste via RTF: this should also be possible for a selection of tiers (i.e. not all tiers)

**Comment by berndmoos** [comment]
This will become Copy HTML

**Comment by sarkipo** [comment]
1.	Generally, „Partitur“ fragments are copied fine as a table, both into Word and into Excel. Fonts and font attributes are preserved.
2.	In Excel, the column width is not preserved at first, but can be set using AutoFit Column Width command.
 
Some remaining issues are illustrated below for MS Word.

3. Hidden tiers are also copied (I would expect it is not the desired behaviour). See in ex. (1) and elsewhere the hidden tiers copied between gg-KuNS and BOR-KuNS.

4. It is important how multiple annotation selection works across tiers. It turns out that in some cases:

(i) Some highlighted annotations are actually not selected (see ex. (2) and (4)), and as a result not copied.
(ii) A rectangular selection with the mouse cannot select all the annotations in the rectangle (see ex. (2)).  
A workaround in those cases is to select more annotations than actually needed in order to copy what is needed; see ex. (3) (extending selection to the right) and (5) (extending selection downwards).
In all these examples, the “Transcription” (type “t”) tier is tx-KuNS, which has word-size events. Sentence-size events in “Annotation” (type “a”) tiers ts-KuNS, fe-KuNS etc. span multiple words. Problems with selection seem to arise when the last tier selected with the mouse spans multiple events. Cf. the timeline in ex. (4) and (5).

[exmaralda-copyHTML.pdf](https://github.com/Exmaralda-Org/exmaralda/files/10093471/exmaralda-copyHTML.pdf)

**Comment by berndmoos** [comment]
> Hidden tiers are also copied (I would expect it is not the desired behaviour)

No, it is not desired behaviour. I (think I) fixed that.

> It is important how multiple annotation selection works across tiers. 

Non-rectangular selection including spanned events is not well-defined. I'm afraid we will have to live with the workaround.

@sarkipo : can you test the new preview at https://exmaralda.org/files/prevDL/experimental.html ?

**Comment by sarkipo** [comment]
> Non-rectangular selection including spanned events is not well-defined. I'm afraid we will have to live with the workaround.

Ok, happily it is not too difficult.

Yes, hidden tiers are not copied any more!

**Comment by berndmoos** [comment]
Done, methinks
