### ISSUE TITLE
Supply built-in formatting via XSL

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#425]
... as suggested by @nolda for DULKO, but also useful for other scenarios. Make this a menu item in the format menu?

**Comment by Herrner** [comment]
TEIDE did something via HTML panels, if I remember correctly...

**Comment by nolda** [comment]
In the former [EXMARaLDA (Dulko)](https://sr.ht/~nolda/exmaralda-dulko/) toolset, there was an XSLT stylesheet [`format-table.xsl`](https://hg.sr.ht/~nolda/exmaralda-dulko/browse/format-table.xsl) which imported (actually, included) the formatting stylesheet [`format.xsl`](https://hg.sr.ht/~nolda/exmaralda-dulko/browse/share/format.xsl) (the latter is also contained in the [current EXMARaLDA source tree](https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/partitureditor/jexmaralda/xsl/dulko/format.xsl) and is transparently called as part of the Dulko transformation scenarios). Since in EXMARaLDA (Dulko), the stylesheets were not part of a JAR file, `format-table.xsl` could be set in the preferences as the "Transcription to format table" stylesheet and called via "Format" > "Apply stylesheet" in order to format Dulko-style EXB files without formatting.

**Comment by nolda** [comment]
As far as I can see, there are two general approaches:
1. Provide a standalone `format-table.xsl` stylesheet (with the `format.xsl` content included) separately from the EXMARaLDA JAR files for the user to set in the preferences.
2. Include `format-table.xsl`  (with adapted `xsl:include/@href`) in the [Dulko stylesheet directory](https://github.com/Exmaralda-Org/exmaralda/tree/master/src/org/exmaralda/partitureditor/jexmaralda/xsl/dulko) and provide some menu entry for calling it.

**Comment by berndmoos** [comment]
I think, I'll go for (2) :-) May take a while, though.

**Comment by berndmoos** [comment]
![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/cd3044f0-c7ed-4819-91f7-7690b808278a)

(No XSL behind the DULKO menu item yet. @nolda : Which one should I use?)

**Comment by nolda** [comment]
I have just added the corresponding XSLT stylesheet in #427.

**Comment by berndmoos** [comment]
I sense that this is done. I really do.
